apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260613-135153-kp53o1x16jix-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260613-135153-kp53o1x16jix.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260613-135153-kp53o1x16jix-service
            port:
              number: 80
