apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260613-135153-kp53o1x16jix-service
spec:
  selector:
    app: enterprise-system-20260613-135153-kp53o1x16jix
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
